name: pack

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Install dependencies
        run: cd pack && dotnet restore MediaInfoNet.csproj

      - name: Build
        run: cd pack && dotnet build MediaInfoNet.csproj --configuration Release --no-restore

      - name: Pack
        run: cd pack && dotnet pack MediaInfoNet.csproj -c Release --no-build -o ../

      - name: Push NuGet package
        # run:  dotnet nuget push "out\*.nupkg" -k ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./*.nupkg
